module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: default
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'JuicyPixels-2.0.2

'
ghc-args:
- -Wall
excluded-modules: []
